#!/bin/sh

usage="This commands set the development mode. Pass 'local'|'localmock'|'npm' to link or not projects locally"

if [[ $# -lt 1 ]] ; then
  echo "$usage"
  exit 1
fi

basedir=`pwd`
inputs=( "$@" )
mode="${inputs[0]}"

get_fullpath(){
  cd $1
  path=`pwd -P`
  echo $path
}

switch_from_symlinks_to_hard_copy(){
  repos=`jq ".projects | keys[]" $basedir/.meta`
  while IFS='' read -r repo; do
    path=`echo "$repo" | sed -e 's/["]//g'`
    if [[ ( $path = commons/* || $path = utils/* ) && -f "$basedir/$path/package.json" ]] ; then
      pkg=`jq ".name" $basedir/$path/package.json | sed -e 's/["]//g'`
      echo "Searching repositories for linked $pkg..."
      links=`find $basedir -path "*/$pkg" -type l`
      while IFS='' read -r link; do
        if [[ ! -z "$link" ]] ; then
          from=`get_fullpath $link`
          to=$link
          if [[ $to = *node_modules* ]] ; then
            echo "Replacing $link"
            rm $link
            echo "     with $from content"
            cp -r $from $to
          fi
        fi
      done <<< "$links"
    fi;
  done <<< "$repos"
}

case $mode in
  local)
    echo "Linking repositories with lerna bootstrap"
    meta exec "rm -rf node_modules"
    lerna bootstrap -- --frozen-lockfile
    ;;

  localmock)
    echo "Switch from linked repositories to local copies"
    switch_from_symlinks_to_hard_copy
    ;;

  npm)
    echo "Downloading all dependencies from npm"
    meta exec "rm -rf node_modules"
    meta exec "yarn install --frozen-lockfile"
    ;;

  *)
    echo "Mode not valid"
    ;;
esac